Ext.define('Personify.utils.ModelManager', {
    config: {
        userModel: 'Personify.model.base.User',
        userAddressModel: 'Personify.model.base.user.Address',
        userEmailModel: 'Personify.model.base.user.Email',
        userNameModel: 'Personify.model.base.user.Name',
        userRoleModel: 'Personify.model.base.user.Role',
        staffModel: 'Personify.model.base.Staff',
        sessionModel: 'Personify.model.base.Session',
        sessionCoordModel: 'Personify.model.base.session.Coord',
        sessionFloorPlanModel: 'Personify.model.base.session.FloorPlan',
        sessionSpeakerModel: 'Personify.model.base.session.Speaker',
        sessionTrackModel: 'Personify.model.base.session.Track',
        relationshipModel: 'Personify.model.base.relationship.Relationship',
        relationshipManagementModel: 'Personify.model.base.relationship.RelationshipManagement',
        contactModel: 'Personify.model.base.contactlisting.Contact',
        contactManagementModel: 'Personify.model.base.contactlisting.ContactManagement',
        contactDetailModel: 'Personify.model.base.contactlisting.ContactDetail',
        contactDetailManagementModel: 'Personify.model.base.contactlisting.ContactDetailManagement',
        referenceModel: 'Personify.model.base.Reference',
        purchaseHistoryModel: 'Personify.model.base.PurchaseHistory',
        purchaseModel: 'Personify.model.base.purchaseHistory.Purchase',
        purchaseSubSystemModel: 'Personify.model.base.purchaseHistory.SubSystem',
        profileModel: 'Personify.model.base.Profile',
        profileAddressModel: 'Personify.model.base.profile.Address',
        profileEmailsModel: 'Personify.model.base.profile.Emails',
        profileEntryModel: 'Personify.model.base.profile.Entry',
        profileGeoModel: 'Personify.model.base.profile.Geo',
        profileNameModel: 'Personify.model.base.profile.Name',
        profileOrganizationModel: 'Personify.model.base.profile.Organization',
        profilePhoneModel: 'Personify.model.base.profile.Phone',
        profilePhotoModel: 'Personify.model.base.profile.Photo',
        productModel: 'Personify.model.base.product.Product',
        productClassModel: 'Personify.model.base.product.ProductClass',
        productListModel: 'Personify.model.base.product.ProductList',
        presenterModel: 'Personify.model.base.Presenter',
        participationModel: 'Personify.model.base.Participation',
        participationCommitteeModel: 'Personify.model.base.participation.Committee',
        notificationModel: 'Personify.model.base.Notification',
        noteModel: 'Personify.model.base.Note',
        materialModel: 'Personify.model.base.Material',
        iCalendarModel: 'Personify.model.base.ICalendar',
        calendarEventModel: 'Personify.model.base.calendar.Event',
        exhibitorModel: 'Personify.model.base.Exhibitor',
        exhibitorListModel: 'Personify.model.base.ExhibitorList',
        directoryModel: 'Personify.model.base.Directory',
        directoryManagementModel: 'Personify.model.base.DirectoryManagement',
        eventMenuModel:'Personify.model.base.EventMenu',
        customerModel: 'Personify.model.base.Customer',
        countryModel: 'Personify.model.base.Country',
        contactModel: 'Personify.model.base.Contact',
        communityModel: 'Personify.model.base.Community',
        cartModel: 'Personify.model.base.Cart', 
        agendaModel: 'Personify.model.base.Agenda',
        addToShoppingCartModel:'Personify.model.base.store.AddToShoppingCart',
        shoppingCartModel: 'Personify.model.base.store.ShoppingCart',
        newsModel: 'Personify.model.news.News'
    },
    constructor: function(config) {
        this.initConfig(config);
    }
});
